config/routes.rb
Rails.application.routes.draw do

  get "/sessions/new", to: "sessions#new", as: :sign_in
  get "/auth/failure", to: "identities#authentication_failure"
  post "/auth/:provider/callback", to: "sessions#create"
  get "/sign_out", to: "sessions#destroy", as: :sign_out

  resources :identities, :users, :families, :reports

  root to: "families#index"

end

app/models/concerns/user/authentication.rb
class User < ActiveRecord::Base
  module Authentication
    extend ActiveSupport::Concern

    included do
      before_create { generate_token :auth_token }
    end

    module ClassMethods
      def from_omniauth(auth)
        find_by(provider: auth["provider"], uid: auth["uid"]) || create_with_omniauth(auth)
      end

      def create_with_omniauth(auth)
        create! do |user|
          user.provider = auth["provider"]
          user.uid = auth["uid"]
          user.first_name = auth["info"]["first_name"]
          user.last_name = auth["info"]["last_name"]
          user.email = auth["info"]["email"]
        end
      end
    end

    private

    def generate_token(column)
      begin
        self[column] = SecureRandom.urlsafe_base64
      end while User.exists?(column => self[column])
    end
  end
end

app/models/family.rb
class Family < ActiveRecord::Base

  belongs_to :user

  validates :user_id,
            :family_name,
            :members_over18, presence: true

  def total_family_members
    total = 0
    total += members_under2 if members_under2
    total += members_2to5 if members_2to5
    total += members_6to12 if members_6to12
    total += members_13to17 if members_13to17
    total += members_over18 if members_over18
    return total
  end
end

app/models/identity.rb
class Identity < OmniAuth::Identity::Models::ActiveRecord
  validates :first_name,
            :last_name, presence: true
  validates :password,
            :password_confirmation, presence: true, on: :create
  validates :password, presence: true, on: :create
  validates :email, presence: true,
                    uniqueness: { case_sensitive: false },
                    format: { with: /\b[A-Z0-9._%a-z\-]+@wavetronix\.com\z/,
                  message: "must be a wavetronix.com account" }

  after_destroy :delete_user

  def generate_token(column)
    begin
      self[column] = SecureRandom.urlsafe_base64
    end while Identity.exists?(column => self[column])
  end

  def delete_user
    user = User.find_by(uid: id)
    user.destroy
  end

  def update_user
    user = User.find_by(uid: id)
    user.first_name = first_name
    user.last_name = last_name
    user.email = email
    user.save
  end

end

app/models/role.rb
class Role < ActiveRecord::Base
  has_and_belongs_to_many :users, :join_table => :users_roles
  belongs_to :resource, :polymorphic => true

  validates :resource_type,
            :inclusion => { :in => Rolify.resource_types },
            :allow_nil => true

  scopify
end

app/models/user.rb
class User < ActiveRecord::Base
  include Authentication
  rolify

  has_many :families

  validates :uid,
            :provider,
            :first_name,
            :last_name,
            :email, presence: true

  validates :email, format: { with: /\b[A-Z0-9._%a-z\-]+@wavetronix\.com\z/,
                  message: "must be a wavetronix.com account" }

  def name
    %W[#{first_name} #{last_name}].join(" ")
  end

  def to_param
    "#{id}-#{name.parameterize}"
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Pundit
  protect_from_forgery with: :exception

  before_action :authenticate!

  rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized

  private

  def authenticate!
    unless current_user
      redirect_to sign_in_path
    end
  end
  helper_method :authenticate!

  def current_user
    @current_user ||= User.find_by(auth_token: cookies[:auth_token]) if cookies[:auth_token]
  end
  helper_method :current_user

  def user_not_authorized(exception)
    policy_name = exception.policy.class.to_s.humanize(capitalize: false)
    flash[:error] = "The #{policy_name.underscore.humanize} prohibits you from performing #{exception.query} on #{exception.record}."
    redirect_to request.referrer || root_path
  end

end

app/controllers/families_controller.rb
class FamiliesController < ApplicationController
  before_action :find_family

  def index
    families
    all_families
  end

  def new
    @family = Family.new
    @family.user_id = current_user.id
  end

  def edit
  end

  def create
    @family = Family.new(family_params)
    @family.user_id = current_user.id if current_user
    if @family.save
      redirect_to families_path, notice: %(Updated "#{@family.family_name}" successfully.)
    else
      render :new
    end
  end

  def update
    if family.update(family_params)
      redirect_to families_path, notice: %(Updated "#{@family.family_name}" successfully.)
    else
      render :edit
    end
  end

  def destroy
    family.destroy
    redirect_to families_path
  end

  private

  def families
    @families ||= current_user.families
  end

  def all_families
    if current_user.has_role?(:admin)
      @all_families = Family.all
      # but listed in order by user_id user last name
    else
      @all_families ||= nil
    end
  end

  def family
    @family ||= current_user.families.find(params[:id])
  end

  def find_family
    @family = Family.find(params[:id]) if params[:id]
  end

  def family_params
    params.require(:family).permit(:user_id, :family_name, :members_under2, :members_2to5, :members_6to12, :members_13to17, :members_over18)
  end

end

app/controllers/identities_controller.rb
class IdentitiesController < ApplicationController
  skip_before_action :authenticate!, only: [:new]
  before_action :find_identity

  def show
  end

  def new
    @identity = env["omniauth.identity"]
  end

  def edit
  end

  def update
    if @identity.update(identity_params)
      @identity.update_user
      redirect_to users_path, notice: %(Updated "#{@identity.first_name}" successfully.)
    else
      render :edit
    end
  end

  def destroy
    @identity.destroy
    redirect_to sign_in_path
  end

  def authentication_failure
    redirect_to sign_in_path, alert: params[:message].humanize
  end

  private

  def identity_params
    params.require(:identity).permit(:first_name, :last_name, :email, :id, :auth_token, :provider)
  end

  def find_identity
    @identity = Identity.find(params[:id]) if params[:id]
  end

end

app/controllers/reports_controller.rb
class ReportsController < ApplicationController
  before_action :find_family, :find_user

  def index
    @families = Family.order("family_name ASC").all
    @users = User.order("last_name, first_name ASC").all
    authorize :report
  end

  private

  def find_family
    @family = Family.find(params[:id]) if params[:id]
  end

  def find_user
    @user = User.find(params[:id]) if params[:id]
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_action :authenticate!, only: [:new, :create]

  def new
  end

  def create
    user = User.from_omniauth(request.env["omniauth.auth"])
    cookies[:auth_token] = {
      value: user.auth_token,
      expires: 30.days.from_now
    }
    uri = session[:referer]
    session[:referer] = nil
    if current_user.families.count < 1
      redirect_path = new_family_path
    else
      redirect_path = root_path
    end
    redirect_path = uri if uri
    redirect_to redirect_path
  end

  def destroy
    cookies.delete :auth_token
    redirect_to sign_in_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :find_user
  after_action :verify_authorized

  def index
    @users = User.order("last_name, first_name ASC").all
    authorize :user
  end

  def show
    authorize @user
  end

  def edit
    authorize @user
  end

  def update
    authorize @user
    if @user.update(user_params)
      redirect_to users_path, notice: %(Updated "#{@user.name}" successfully.)
    else
      render :edit
    end
  end

  def destroy
    authorize @user
    @user.families.destroy_all
    @user.destroy
    redirect_to users_path, notice: %(Deleted "#{@user.name}" successfully.)
  end

private

  def find_user
    @user = User.find(params[:id]) if params[:id]
  end

  def user_params
    params.require(:user).permit(:first_name, :last_name, :email)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
  def full_title(page_title = nil)
    if page_title.present?
      "Wavetronix Family Survey - #{page_title}"
    else
      "Wavetronix Family Survey"
    end
  end
end

app/views/application/_flash.html.erb
<% flash.each do |name, msg| %>
  <%= content_tag :div, data: { alert: "" }, class: "alert-box #{name}" do %>
    <%= msg %>
    <%= link_to "X", nil, class: "close" %>
  <% end %>
<% end %>

app/views/application/_site_footer.html.erb
<footer class="site-footer">
  <hr/>
  <section class="row">
    <div class="medium-7 columns">
      <ul class="inline-list">
        <li>&copy; <%= Time.now.year %> Wavetronix LLC.</li>
      </ul>
    </div>
    <div class="medium-5 columns end hide-for-small">
      <ul class="inline-list right">
        <% if current_user %>
          <li>
            <%= current_user.name %>
          </li>
          <li><%= link_to "Sign Out", sign_out_path, title: "Sign out" %></li>
        <% end %>
      </ul>
    </div>
  </section>
</footer>

app/views/application/_site_header.html.erb
<header class="site-header">
  <nav class="tab-bar">
    <% if current_user && current_user.has_role?(:admin) %>
      <section class="left-small">
        <%= link_to content_tag(:span), nil, class: 'left-off-canvas-toggle menu-icon' %>
      </section>
    <% end %>
    <section class="middle tab-bar-section">
      <h1><%= link_to image_tag('nav_logo.svg', alt: 'Wavetronix'), root_path, class: 'top-bar-site-icon' %></h1>
    </section>
  </nav>

  <%= render "flash" %>

  <% if current_user && current_user.has_role?(:admin) %>
    <aside class="left-off-canvas-menu">
      <ul class="off-canvas-list">
        <li><label>Wavetronix Family Survey</label></li>
        <li>
          <%= link_to "Reports", reports_path %>
        </li>
        <li>
          <%= link_to "Users", users_path %>
        </li>
        <li>
          <%= link_to "My Family", root_path %>
        </li>
        <li>
          <%= link_to sign_out_path do %>
            Sign out
          <% end %>
        </li>
      </ul>
    </aside>
  <% end %>
</header>

app/views/families/_form.html.erb
<%= form_for @family do |f| %>
  <%= content_tag :div, class: 'alert-box radius alert' do %>
    <h4><%= pluralize @family.errors.count, 'error' %> kept this form from submitting:</h4>
    <ul>
      <% if @family.members_over18.blank? %>
        <p>There cannot be a household without a person over 18. Please remember to include the heads of household.</p>
      <% else %>
        <% @family.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      <% end %>
    </ul>
  <% end if @family.errors.any? %>
  <div class="columns">
    <%= f.label :family_name %>
    <%= f.text_field :family_name %>
    <p>For each field below, please type in how many in the family are in the age bracket that are planning to attend. Please note that this is the age they will be by August 2nd of this year. Please include the head of household and their spouse as well!</p>
    <%= f.label "Children under 2 years old" %>
    <%= f.number_field :members_under2, :placeholder => "0" %>
    <%= f.label "Children 2-5 years old" %>
    <%= f.number_field :members_2to5, :placeholder => "0" %>
    <%= f.label "Children 6-12 years old" %>
    <%= f.number_field :members_6to12, :placeholder => "0" %>
    <%= f.label "Children 13-17 years old" %>
    <%= f.number_field :members_13to17, :placeholder => "0" %>
    <%= f.label "Family members 18 years or older" %>
    <%= f.number_field :members_over18, :placeholder => "0" %>

    <p>To create a another new family (for example, if your children do not live at home and have their own seperate family), you will be given a chance to do so in the next step.</p>
  </div>
  <div class="row">
    <div class="medium-6 columns">
      <%= f.submit "Add your family", class: 'button radius expand' %>
    </div>
  </div>
<% end %>

app/views/families/edit.html.erb
<% content_for :title, "Edit Family" %>

<div class="row">
  <div class="columns">
    <h1>Edit Family</h1>
    <p>Fill out this form with the information for the members of the family currently living in the same household. All information on this form should be relevant for August 2nd of this year.</p>
  </div>
  <%= render 'form' %>
</div>

app/views/families/index.html.erb
<div class="row">
  <h1>Families of <%= current_user.name %></h1>
  <% @families.each do |family| %>
    <div class="row panel family-panel">
      <div class="medium-8 columns">
        <h3><%= family.family_name %> Family</h3>
        <p>On August 1st, the <%= family.family_name %> family will have a total of <%= pluralize(family.total_family_members, "member") %>.</p>
        <% if family.members_under2 && family.members_under2 > 0 %>
          Family members 2 and under = <%= family.members_under2 %><br/>
        <% end %>
        <% if family.members_2to5 && family.members_2to5 > 0 %>
          Family members 2 to 5 = <%= family.members_2to5 %><br/>
        <% end %>
        <% if family.members_6to12 && family.members_6to12 > 0 %>
          Family members 6 to 12 = <%= family.members_6to12 %><br/>
        <% end %>
        <% if family.members_13to17 && family.members_13to17 > 0 %>
          Family members 13 to 17 = <%= family.members_13to17 %><br/>
        <% end %>
        <% if family.members_over18 && family.members_over18 > 0 %>
          Family members 18 and over = <%= family.members_over18 %><br/>
        <% end %>
      </div>
      <div class="medium-4 text-right columns">
        <%= button_to "Edit the #{family.family_name} family", edit_family_path(family), class: "button radius", method: :get %>
        <%= button_to "Delete the #{family.family_name} family", family_path(family), class: "button radius alert tiny", data: { confirm: %(Are you sure you wnt to delete the "#{family.family_name}?" This cannot be undone.) }, method: :delete %>
      </div>
    </div>
  <% end %>
</div>
<div class="row">
  <h3>Step Three <small>(optional)</small></h3>
  <p>If you have decendents that do not live at home and have their own families, please add them by clicking the button below.</p>
  <%= button_to "Register a new family", new_family_path, class: "button radius", method: :get %>
</div>
<hr/>
<div class="row">
  <h3>Step Four</h3>
  <p>If you have completed your family and decendents - Congratulations! You are all done! You can <%= link_to "log out", sign_out_path %>, or edit your family above. Remember all changes must be made by Friday, January 15th.</p>
</div>

app/views/families/new.html.erb
<% content_for :title, "New Family" %>

<div class="row">
  <div class="columns">
    <h1>Step Two</h1>
    <h2>Family Information</h2>
    <p>Please enter the information below for your immediate family, currently living with you, that plan on attending the trip. If you don't have a spouse or they don't plan on attending, just leave their name blank. All information on this form should be relevant for September of this year.</p>
  </div>
  <%= render 'form' %>
</div>

app/views/identities/edit.html.erb
<% content_for :title, @identity.first_name %>

<header>
  <h1>
    <%= @identity.first_name %>
  </h1>
</header>

<%= form_for @identity do |f| %>
  <% if @identity.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize @identity.errors.count, "error" %> prohibited this event from being saved:</h2>
    <ul>
    <% @identity.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
  <% end %>
  <%= f.label :first_name %>
  <%= f.text_field :first_name %>

  <%= f.label :last_name %>
  <%= f.text_field :last_name %>

  <%= f.label :email %>
  <%= f.email_field :email %>

  <%= f.submit :class => 'button default' %>
<% end %>

app/views/identities/new.html.erb
<% content_for :title, "Register your family" %>
<h1>Step One</h1>
<h2>Employee Information</h2>
<p>Please enter the information below for you, the employee.</p>

<%= form_tag "/auth/identity/register" do %>
  <% if @identity && @identity.errors.any? %>
    <div class="error_messages">
      <h2><%= pluralize(@identity.errors.count, "error") %> prohibited this account from being saved:</h2>
      <ul>
      <% @identity.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>


  <%= label_tag "Your first name" %>
  <%= text_field_tag :first_name, @identity.try(:first_name) %>

  <%= label_tag "Your last name" %>
  <%= text_field_tag :last_name, @identity.try(:last_name) %>


  <%= label_tag "Your work email" %>
  <%= email_field_tag :email, @identity.try(:email) %>

  <p>Please enter in a password so you can edit your family information later if needed</p>
  <div class="row">
    <div class="medium-6 columns">
      <%= label_tag :password %>
      <%= password_field_tag :password %>
    </div>
    <div class="medium-6 columns">
      <%= label_tag :password_confirmation %>
      <%= password_field_tag :password_confirmation %>
    </div>
  </div>

  <%= submit_tag "Continue to Step Two", class: "button radius" %>
<% end %>

app/views/identities/show.html.erb
<% content_for :title, "#{@identity.first_name} #{@identity.last_name}" %>
<h1><%= "#{@identity.first_name} #{@identity.last_name}" %></h1>
<h2 class="subheader">
  <%= @identity.email %>
</h2>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="<%= locale %>">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title><%= full_title yield(:title) %></title>

    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "vendor/modernizr" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
  </head>

  <body>
    <div class="off-canvas-wrap" data-offcanvas>
      <div class="inner-wrap">
        <%= render "site_header" %>
        <main class="row">
          <div class="columns">
            <%= yield %>
          </div>
        </main>
        <%= render "site_footer" %>
        <div class="row">
          <div class="columns">
            <%= content_tag :div, class: "panel radius" do %>
              <%= debug params %>
            <% end if Rails.env.in? %w[development] %>
          </div>
        </div>
        <a class="exit-off-canvas"></a>
      </div>
    </div>
  </body>
</html>

app/views/reports/index.html.erb
<div class="row">
  <div class="medium-6 columns">
    <h1>All Families</h1>
    <h3>Totals</h3>
    <p><b><%= pluralize(@families.count, "family") %></b></p>
    <p><b><%= pluralize(@families.sum(:members_under2), "member") %></b> under 2 years old.</p>
    <p><b><%= pluralize(@families.sum(:members_2to5), "member") %></b> between 2 and 5 years old.</p>
    <p><b><%= pluralize(@families.sum(:members_6to12), "member") %></b> between 6 and 12 years old.</p>
    <p><b><%= pluralize(@families.sum(:members_13to17), "member") %></b> between 13 and 17 years old.</p>
    <p><b><%= pluralize(@families.sum(:members_over18), "member") %></b> over 18 years old.</p>

    <% @families.each do |family| %>
      <div class="row panel family-panel">
        <h3><%= family.family_name %> Family <small>(Family of <%= family.user.name %>)</small></h3>
        <p>On August 1st, the <%= family.family_name %> family will have a total of <b><%= pluralize(family.total_family_members, "member") %></b>.</p>
        <% if family.members_under2 && family.members_under2 > 0 %>
          <b><%= pluralize(family.members_under2, "member") %></b> under 2 years old.<br/>
        <% end %>
        <% if family.members_2to5 && family.members_2to5 > 0 %>
          <b><%= pluralize(family.members_2to5, "member") %></b> between 2 and 5 years old.<br/>
        <% end %>
        <% if family.members_6to12 && family.members_6to12 > 0 %>
          <b><%= pluralize(family.members_6to12, "member") %></b> between 6 and 12 years old.<br/>
        <% end %>
        <% if family.members_13to17 && family.members_13to17 > 0 %>
          <b><%= pluralize(family.members_13to17, "member") %></b> between 13 and 17 years old.<br/>
        <% end %>
        <% if family.members_over18 && family.members_over18 > 0 %>
          <b><%= pluralize(family.members_over18, "member") %></b> over 18 years old.</p>
        <% end %>
        <p></p>
        <ul class="button-group even-2">
          <li>
            <%= button_to "Edit Family", edit_family_path(family), class: "button", method: :get %>
          </li>
          <li>
            <%= button_to "Delete family", family_path(family), class: "button alert", data: { confirm: %(Are you sure you wnt to delete the "#{family.family_name}?" This cannot be undone.) }, method: :delete %>
          </li>
        </ul>
          <%= button_to "See all families of #{family.user.name}", user_path(family.user), class: "button expand info", method: :get %>
      </div>
    <% end %>
  </div>
  <div class="medium-6 columns">
    <h1>Employees signed up</h1>
    <h3>Totals</h3>
    <p><b><%= @users.count %> employees</b> have signed up.</p>
    <p><b><%= @families.all.map(&:total_family_members).sum %> people</b> are accounted for.</p>
    <table width="100%">
      <thead>
        <tr>
          <th>Employee</th>
          <th>Families</th>
          <th>Total Family Members</th>
        </tr>
      </thead>
      <tbody>
        <% @users.each do |user| %>
          <tr>
            <td>
              <strong><%= user.last_name %>, <%= user.first_name %></strong>
            </td>
            <td class="text-center">
              <%= link_to "#{user.families.count}",user_path(user) %>
            </td>
            <td class="text-center"><%= user.families.all.map(&:total_family_members).sum %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/users/_user.html.erb
<tr>
  <td>
    <%= link_to edit_user_path(user), title: %(Edit "#{user.name}") do %>
      <strong><%= user.name %></strong>
    <% end %>
  </td>
  <td class="hide-for-small"><%= user.email %></td>
  <td class="text-right"><%= user.families.count %></td>
  <td class="hide-for-small">
    <%= link_to 'Delete User', user_path(user), class: 'button tiny radius delete', data: { confirm: %(Are you sure you want to delete "#{user.name}?" This cannot be undone.) }, method: :delete %>
  </td>
</tr>

app/views/users/edit.html.erb
<% content_for :title, "Edit #{@user.name}" %>
<h1><%= "Edit #{@user.name}" %></h1>

<%= form_for @user do |f| %>
  <%= f.label :first_name %>
  <%= f.text_field :first_name %>
  <%= f.label :last_name %>
  <%= f.text_field :last_name %>
  <%= f.label :email %>
  <%= f.text_field :email %>
  <div class="row">
    <%= f.submit class: 'button radius expand' %>
  </div>
<% end %>

app/views/users/index.html.erb
<% content_for :title, "Users" %>
<h1>Users</h1>
<p>This is a list of all of the Employees who have currently at least created an account.</p>

<table>
  <thead>
    <tr>
      <th>Employee</th>
      <th class="hide-for-small">Email</th>
      <th>Families Created</th>
      <th class="hide-for-small">Delete</th>
    </tr>
  </thead>
  <tbody>
    <%= render @users %>
  </tbody>
</table>

app/views/users/show.html.erb
<% content_for :title, "#{@user.name}'s Family" %>

<h1><%= @user.name %>'s Family</h1>
<h3><%= pluralize(@user.families.count, "family") %> with <%= @user.families.all.map(&:total_family_members).sum %> people</b></p>

<% @user.families.each do |family| %>
  <div class="row panel family-panel">
    <div class="medium-8 columns">
      <h3><%= family.family_name %> Family</h3>
      <p>On August 1st, the <%= family.family_name %> family will have a total of <%= pluralize(family.total_family_members, "member") %>.</p>
      <p><% if family.members_under2 && family.members_under2 > 0 %>
        Family members 2 and under = <%= family.members_under2 %><br/>
      <% end %>
      <% if family.members_2to5 && family.members_2to5 > 0 %>
        Family members 2 to 5 = <%= family.members_2to5 %><br/>
      <% end %>
      <% if family.members_6to12 && family.members_6to12 > 0 %>
        Family members 6 to 12 = <%= family.members_6to12 %><br/>
      <% end %>
      <% if family.members_13to17 && family.members_13to17 > 0 %>
        Family members 13 to 17 = <%= family.members_13to17 %><br/>
      <% end %>
      <% if family.members_over18 && family.members_over18 > 0 %>
        Family members 18 and over = <%= family.members_over18 %></p>
      <% end %>
    </div>
    <div class="medium-4 text-right columns">
      <%= button_to "Edit the #{family.family_name} family", edit_family_path(family), class: "button radius", method: :get %>
      <%= button_to "Delete the #{family.family_name} family", family_path(family), class: "button radius alert tiny", data: { confirm: %(Are you sure you wnt to delete the "#{family.family_name}?" This cannot be undone.) }, method: :delete %>
    </div>
  </div>
<% end %>